[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.5", features = ["audio"]}
phf = { version = "0.11.2", features = ["macros"] }

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
