[package]
name = "minesweeper_ggez"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.5"
rand = "*"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
